### ISSUE TITLE
Stricter user gestures for touch

### ISSUE THREAD

**Issue by RByers** [WICG/interventions#13]
Building on #12, no browser does a great job of this today for touch input.  The fundamental problem is that, unlike mouse, the gesture for scrolling is ambiguous - may or may not be a substantial interaction with the page (eg. consider a sliding toggle switch).

Problem details and a specific proposal are [here](https://docs.google.com/document/d/1oF1T3O7_E4t1PYHV6gyCwHxOi3ystm0eSL5xZu7nvOg/edit#)

**Comment by singhvijayy** [comment]
Will touchstart, touchmove and touchend be supported for as triggers for starting, continuing and ending of a path on a canvas element?

**Comment by RByers** [comment]
> Will touchstart, touchmove and touchend be supported as triggers for starting, continuing and ending a path on a canvas element?

There shouldn't be any change here for anything to do with canvas (drawing on a canvas never requires a "user gesture").  But such code could be affected by #18 if the touch listeners are on the document and aren't already using `touch-action: none` to declaratively disable touch scrolling over the canvas.

**Comment by toddreifsteck** [comment]
@RByers Is this issue intended to cover everything within that proposal document? I'm asking because that document seems to cover a few somewhat separate use-cases/goals/possible implementation details.

**Comment by RByers** [comment]
@toddreifsteck sorry I missed the above.  Yes this issue covers figuring out what the precise heuristics should be for touch, and getting them standardized.

**Comment by domenic** [comment]
I believe this issue is now solved, in the HTML Standard. In particular, it's covered by the [activation triggering input event](https://html.spec.whatwg.org/#activation-triggering-input-event) definition, which was recently settled (with tests!) in https://github.com/whatwg/html/pull/7248.

There's still a concern from @flackr at https://github.com/whatwg/html/issues/7341 about how pointer vs. touch events are treated differently, but we can track that over on the HTML Standard repository. As such, we'll close this issue, as part of the larger project of archiving this repository (see #72).
